# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 18
#     commands:
#       - npm install
#   build:
#     commands:
#       - npm run build

# artifacts:
#   base-directory: dist
#   files:
#     - '**/*'


version: 0.2

env:
  variables:
    S3_BUCKET: "takshil-bucket-test"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing NPM dependencies..."
      - npm install
  build:
    commands:
      - echo "Building React app..."
      - npm run build
  post_build:
    commands:
      - echo "Syncing build folder to S3 bucket: $S3_BUCKET"
      - aws --version
      - aws s3 sync build/ s3://$S3_BUCKET/ --delete
      - echo "S3 sync completed."

artifacts:
  base-directory: build
  files:
    - '**/*'

